language: python

python:
  - 2.7
  - 3.5

sudo: true

services:
  - docker

before_install:
  - pwd
  - echo $TRAVIS_PYTHON_VERSION
  - docker run -d -p 8020:8020 -p 50070:50070 mdurant/docker_images:hadoop
  - sleep 20  # Wait for namenode and datanode

install:
  - source continuous_integration/run.sh

script:
  - py.test hdfs3 -vv
