language: generic
sudo: false
dist: trusty
services:
  - docker

env:
  matrix:
    - PYTHON=2.7  CONDA_ENV=/opt/conda/envs/py27
    - PYTHON=3.5  CONDA_ENV=/opt/conda

before_install:
  - source continuous_integration/setup_hdfs.sh

install:
  - docker exec -it $CONTAINER_ID $CONDA_ENV/bin/python setup.py install

script:
  - docker exec -it $CONTAINER_ID $CONDA_ENV/bin/py.test hdfs3 -s -vv
  - if [[$PYTHON == "2.7"]]; then docker exec -it $CONTAINER_ID $CONDA_ENV/bin/flake8 hdfs3; fi
