package:
    name: libhdfs3
    version: 2.2.30

source:
    git_url: https://github.com/PivotalRD/libhdfs3.git

requirements:
    build:
        - libprotobuf
        - libgsasl
        - libntlm
        - boost ==1.60
        - cmake
    run:
        - libprotobuf
        - libgsasl
        - libntlm
        - boost ==1.60

about:
  home: https://github.com/PivotalRD/libhdfs3
  license: Apache
  summary: A Native C/C++ HDFS Client
